// Generated by https://quicktype.io

export interface Alumno {
    id:               number;
    primer_Nombre:    string;
    segundo_Nombre:   string;
    primer_Apellido:  string;
    segundo_Apellido: string;
    identificacion:   string;
    id_usuario:       number;
    createdAt:        string;
    updatedAt:        string;
    Alumno_cursos:    any[];
    Usuario:          Usuario;
}

export interface Usuario {
    id:         number;
    usuario:    string;
    contrasena: string;
    email:      string;
    nombre:     string;
    idCuenta:   number;
    createdAt:  string;
    updatedAt:  string;
}
